name: Aplicar Terraform

on:
  workflow_call:

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Descargar código del repositorio
        uses: actions/checkout@v4

      - name: 🔑 Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
          
      - name: Configurar Terraform
        run: terraform init

      - name: Validar Terraform
        run: terraform validate

      - name: Plan de Terraform
        run: terraform plan -out=tfplan

      - name: Guardar Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

      - name: Aplicar Terraform
        run: terraform apply -auto-approve tfplan