name: Aplicar Terraform

on:
  workflow_call:

jobs:
  terraform-validations:
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
          
      - name: Configurar Terraform
        run: terraform init

      - name: Validar Terraform
        run: terraform validate