name: Importar Recursos en Terraform

on:
  workflow_call:
    inputs:
      api_id:
        required: true
        type: string
      vpc_id:
        required: true
        type: string
      lambda_arns:
        required: true
        type: string

jobs:
  terraform-import:
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Descargar código del repositorio
        uses: actions/checkout@v4

      - name: 🔑 Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Configurar Terraform
        run: terraform init

      - name: Importar API Gateway
        if: inputs.api_id != ''
        run: terraform import module.api_gateway.aws_api_gateway_rest_api.api ${{ inputs.api_id }}

      - name: Importar VPC
        if: inputs.vpc_id != ''
        run: terraform import module.vpc.aws_vpc.this ${{ inputs.vpc_id }}

      - name: Importar Lambda Functions
        if: inputs.lambda_arns != ''
        run: |
          for ARN in ${{ inputs.lambda_arns }}; do
            FUNC_NAME=$(echo $ARN | awk -F: '{print $NF}')
            terraform import module.lambda["$FUNC_NAME"].aws_lambda_function.lambda_function $ARN
          done
